INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (256,'Greenbush Grounds','ALB01','Riverside Park','Rensselaer','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (257,'Fourth Avenue Grounds','ALT01','Columbia Park','Altoona','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (258,'Edison Field; Anaheim Stadium','ANA01','Angel Stadium of Anaheim','Anaheim','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (259,NULL,'ARL01','Arlington Stadium','Arlington','TX','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (260,'The Ballpark in Arlington; Ameriquest Field in Arlington; Rangers Ballpark in Arlington','ARL02','Globe Life Park in Arlington','Arlington','TX','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (261,'Fulton County Stadium; Atlanta Stadium','ATL01','Atlanta-Fulton County Stadium','Atlanta','GA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (262,'Centennial Olympic Stadium','ATL02','Turner Field','Atlanta','GA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (263,'SunTrust Park','ATL03','Truist Park','Atlanta','GA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (264,'Monumental Park','BAL01','Madison Avenue Grounds','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (265,NULL,'BAL02','Newington Park','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (266,'Huntingdon Avenue Park; American Association Park','BAL03','Oriole Park I','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (267,'Union Park; Union Association Grounds','BAL04','Belair Lot','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (269,NULL,'BAL06','Oriole Park II','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (270,'Union Park','BAL07','Oriole Park III','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (271,'American League Park','BAL09','Oriole Park IV','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (272,'Oriole Park V','BAL10','Terrapin Park','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (273,'Baltimore Memorial Stadium','BAL11','Memorial Stadium','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (274,'Camden Yards','BAL12','Oriole Park at Camden Yards','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (275,'Walpole Street Grounds; Union Baseball Grounds; Boston National League Base Ball Park; Boston Base Ball Grounds','BOS01','South End Grounds I','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (276,'Union Park; Union Athletic Grounds; Union Grounds','BOS02','Dartmouth Grounds','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (277,'Grand Pavilion','BOS03','South End Grounds II','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (278,NULL,'BOS04','Congress Street Grounds','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (279,'Boston National League Base Ball Park','BOS05','South End Grounds III','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (280,NULL,'BOS06','Huntington Avenue Baseball Grounds','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (281,NULL,'BOS07','Fenway Park','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (282,'National League Park','BOS08','Braves Field','Boston','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (283,'Riverside Park','BUF01','Riverside Grounds','Buffalo','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (284,NULL,'BUF02','Olympic Park I','Buffalo','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (285,'Buffalo Baseball Park','BUF03','Olympic Park II','Buffalo','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (286,'International Fair Association Grounds','BUF04','Federal League Park','Buffalo','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (287,'League Park','CAN01','Mahaffey Park','Canton','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (288,NULL,'CAN02','Pastime Park','Canton','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (289,'Union Base-Ball Grounds; White-Stocking Park','CHI01','Lake Front Park I','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (290,NULL,'CHI02','23rd Street Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (291,'Lake-Shore Park; Lake Front Park; Lake Park','CHI03','Lake Front Park II','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (292,'Cricket Club Grounds; Union Base Ball Park; 39th Street Grounds','CHI05','South Side Park I','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (293,NULL,'CHI06','West Side Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (294,'White Stocking Park; Brotherhood Park','CHI07','South Side Park II','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (295,'West Side Park; Garden City Athletic Club','CHI08','West Side Grounds','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (296,'Schorling Park; Schorling''s Park II; Cole''s Park; American Giants Park; White Sox Park','CHI09','South Side Park III','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (297,'White Sox Park','CHI10','Comiskey Park I','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (298,'Weeghman Park; Cubs Park','CHI11','Wrigley Field','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (299,'U.S. Cellular Field; White Sox Park; Comiskey Park II; Guaranteed Rate Field','CHI12','Rate Field','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (300,'Union Grounds; Union Cricket Club Grounds','CIN01','Lincoln Park Grounds','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (301,'Brighton Park; Cincinnati Baseball Park','CIN02','Avenue Grounds','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (302,'Bank-Street Grounds; Union Athletic Park','CIN03','Bank Street Grounds','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (303,'Cincinnati Base Ball Grounds; Western Avenue Grounds; American Park','CIN04','League Park I','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (304,NULL,'CIN05','League Park II','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (305,'League Park III','CIN06','Palace of the Fans','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (306,'Redland Field','CIN07','Crosley Field','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (307,'Riverfront Stadium','CIN08','Cinergy Field','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (308,NULL,'CIN09','Great American Ballpark','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (309,NULL,'CLE01','National Association Grounds','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (310,'National League Park I; Kennard Street Baseball Grounds; Kennard Street Park','CLE02','League Park I','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (311,'National League Park II; American Association Park; Association Park; Association Park','CLE03','League Park II','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (312,'Players League Park','CLE04','Brotherhood Park','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (313,'National League Park III','CLE05','League Park III','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (314,'Dunn Field','CLE06','League Park IV','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (315,'Municipal Stadium; Lakefront Stadium; Cleveland Municipal Stadium','CLE07','Cleveland Stadium','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (316,'Jacobs Field','CLE08','Progressive Field','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (317,NULL,'CLE09','Cedar Avenue Driving Park','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (318,NULL,'CLL01','Euclid Beach Park','Collinwood','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (319,NULL,'COL01','Recreation Park I','Columbus','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (320,NULL,'COL02','Recreation Park II','Columbus','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (321,NULL,'COL03','Neil Park I','Columbus','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (322,NULL,'COL04','Neil Park II','Columbus','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (323,NULL,'COV01','Star Baseball Park','Covington','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (324,NULL,'DAY01','Fairview Park','Dayton','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (325,'Bears Stadium','DEN01','Mile High Stadium','Denver','CO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (326,NULL,'DEN02','Coors Field','Denver','CO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (327,NULL,'DET01','Recreation Park','Detroit','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (328,NULL,'DET02','Bennett Park','Detroit','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (329,'West End Park','DET03','Burns Park','Detroit','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (330,'Navin Field; Briggs Stadium','DET04','Tiger Stadium','Detroit','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (331,NULL,'DET05','Comerica Park','Detroit','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (332,'Dover Grounds','DOV01','Fairview Park Fair Grounds','Dover','DE','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (333,'Elmira Grounds','ELM01','Maple Avenue Driving Park','Elmira','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (334,'Grand Duchess; Hamilton Field','FOR01','Kekionga Ball Grounds','Fort Wayne','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (335,NULL,'FOR03','Jailhouse Flats','Fort Wayne','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (336,NULL,'FTB01','Fort Bragg Field','Fort Bragg','NC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (337,NULL,'GEA01','Geauga Lake Grounds','Bainbridge Township','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (338,NULL,'GLO01','Gloucester Point Grounds','Gloucester City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (339,NULL,'GLO02','Gloucester Fireworks Park','Gloucester City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (340,NULL,'GRA01','Ramona Park','Grand Rapids','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (341,'Federal Baseball Park','HAR01','Harrison Field','Harrison','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (342,NULL,'HOB01','Elysian Fields','Hoboken','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (343,NULL,'HON01','Aloha Stadium','Honolulu','HI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (344,'Estadio Superior; Estadio Ángel Castro; Estadio de Béisbol Mecano; Millón de Tuercas','HOU01','Colt Stadium','Houston','TX','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (345,NULL,'HOU02','Astrodome','Houston','TX','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (346,'The Ballpark at Union Station; Enron Field; Astros Field; Minute Maid Park','HOU03','Daikin Park','Houston','TX','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (347,NULL,'HRT01','Hartford Ball Club Grounds','Hartford','CT','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (348,NULL,'HRT02','Hartford Trotting Park','Hartford','CT','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (349,'South Street Grounds; National Park','IND01','South Street Park','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (350,'Tinker Park; Athletic Park','IND02','Seventh Street Park I','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (351,'Bruce Park; Bruce''s Park','IND03','Bruce Grounds','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (352,'Tinker Park; Athletic Park','IND04','Seventh Street Park II','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (353,'Tinker Park; Athletic Park','IND05','Seventh Street Park III','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (354,'Athletic Park II; League Park','IND06','Indianapolis Park','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (355,'Washington Park','IND07','Federal League Park','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (356,'Windsor Beach Grounds','IRO01','Windsor Beach','Irondequoit','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (357,'Oakland Athletic Association Field','JER01','Oakdale Park','Jersey City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (358,'Jersey City Roosevelt Stadium','JER02','Roosevelt Stadium','Jersey City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (359,NULL,'KAN01','Athletic Park','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (360,'Association Park I; League Park','KAN02','Association Park','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (361,NULL,'KAN03','Exposition Park','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (362,'Gordon and Koppel Stadium; Gordon-Koppel Field; Gordon & Koppel Field; Gordon & Koppel Stadium','KAN04','Gordon and Koppel Field','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (363,'Muehlebach Field; Ruppert Stadium; Blues Stadium','KAN05','Municipal Stadium','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (364,'Royals Stadium','KAN06','Kauffman Stadium','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (365,'Walte''s Pasture','KEO01','Perry Park','Keokuk','IA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (366,NULL,'LAS01','Cashman Field','Las Vegas','NV','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (367,'The Ballpark; Cracker Jack Stadium; The Ballpark at Disney''s Wide World of Sports; Champion Stadium','LBV01','The Stadium at the ESPN Wide World of Sports','Lake Buena Vista','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (368,'Olympic Stadium; Stadium at Queen Elizabeth Olympic Park','LON01','London Stadium','London','ENG','UK');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (369,'Los Angeles Coliseum; L.A. Coliseum; Olympic Stadium','LOS01','Los Angeles Memorial Coliseum','Los Angeles','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (370,NULL,'LOS02','Wrigley Field','Los Angeles','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (371,'Chavez Ravine','LOS03','Dodger Stadium','Los Angeles','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (372,'Louisville Baseball Grounds','LOU01','Louisville Baseball Park','Louisville','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (373,NULL,'LOU02','Eclipse Park I','Louisville','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (374,NULL,'LOU03','Eclipse Park II','Louisville','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (375,NULL,'LOU04','Eclipse Park III','Louisville','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (376,NULL,'LUD01','Ludlow Baseball Park','Ludlow','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (377,'Maspeth Ball Grounds; Long Island Recreation Grounds','MAS01','Long Island Grounds','Maspeth','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (378,'Joe Robbie Stadium; Pro Player Park; Pro Player Stadium; Dolphins Stadium; Dolphin Stadium; Land Shark Stadium; Sun Life Stadium','MIA01','Hard Rock Stadium','Miami','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (379,'Marlins Park','MIA02','loanDepot park','Miami','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (380,'Mansfield Park; Fort Hill Grounds','MID01','Mansfield Club Grounds','Middletown','CT','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (381,'Milwaukee Base-Ball Grounds','MIL01','Eclipse Park','Milwaukee','WI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (382,NULL,'MIL02','Wright Street Grounds','Milwaukee','WI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (383,'Borchert Field; Borchert Park','MIL03','Athletic Park','Milwaukee','WI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (384,NULL,'MIL04','Lloyd Street Grounds','Milwaukee','WI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (385,'Milwaukee County Stadium; Milwaukee County Municipal Stadium','MIL05','County Stadium','Milwaukee','WI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (386,'Miller Park','MIL06','American Family Field','Milwaukee','WI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (387,NULL,'MIN01','Athletic Park','Minneapolis','MN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (388,'Met Stadium','MIN02','Metropolitan Stadium','Bloomington','MN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (389,'Metrodome','MIN03','Hubert H. Humphrey Metrodome','Minneapolis','MN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (390,NULL,'MIN04','Target Field','Minneapolis','MN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (391,'Estadio de Béisbol Monterrey; Estadio Mobil Super; Palacio Sultán','MNT01','Estadio Monterrey','Monterrey','Nuevo Leon','MX');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (392,'Jarry Park Stadium; Jarry Park','MON01','Stade Parc Jarry','Montreal','QC','CA');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (393,'Olympic Stadium','MON02','Stade Olympique','Montreal','QC','CA');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (394,'Brewster Park; Hamilton Park','NEW01','Howard Avenue Grounds','New Haven','CT','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (395,'Brewster Park; Howard Avenue Grounds','NEW02','Hamilton Park','New Haven','CT','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (396,NULL,'NEW03','Beyerle''s Park','Newburgh Township','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (397,'Wiedenmeyer''s Park','NWK01','Wiedenmayer''s Park','Newark','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (398,NULL,'NYC01','Union Grounds','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (399,'Capitoline Skating Lake and Base Ball Ground','NYC02','Capitoline Grounds','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (400,'Polo Field East; the polo grounds','NYC03','Polo Grounds I (Southeast Diamond)','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (401,'Polo Field West; Metropolitan Field','NYC04','Polo Grounds II (Southwest Diamond)','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (402,NULL,'NYC05','Washington Park I','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (403,NULL,'NYC06','Metropolitan Park','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (404,'Grauer''s Ridgewood Park; Grauer''s Woods; Ridgewood Grounds','NYC07','Ridgewood Park I','Queens','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (405,NULL,'NYC08','Washington Park II','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (406,'New Polo Grounds; Manhattan Field','NYC09','Polo Grounds III','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (407,'New Polo Grounds; Brotherhood Park','NYC10','Polo Grounds IV','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (408,NULL,'NYC11','Eastern Park','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (409,NULL,'NYC12','Washington Park III','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (410,'American League Park','NYC13','Hilltop Park','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (411,'Brush Stadium','NYC14','Polo Grounds V','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (412,NULL,'NYC15','Ebbets Field','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (413,NULL,'NYC16','Yankee Stadium I','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (414,'Flushing Meadow Park Municipal Stadium; William A. Shea Municipal Stadium','NYC17','Shea Stadium','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (415,'Wallace''s Ridgewood Park; Wallace Grounds','NYC18','Ridgewood Park II','Queens','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (416,NULL,'NYC19','Washington Park IV','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (417,NULL,'NYC20','Citi Field','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (418,NULL,'NYC21','Yankee Stadium II','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (419,'Oakland Coliseum; Network Associates Coliseum; McAfee Coliseum; Overstock.com Coliseum; O.co Coliseum; RingCentral Coliseum','OAK01','Oakland-Alameda County Coliseum','Oakland','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (420,'TD Ameritrade Park Omaha','OMA01','Charles Schwab Field Omaha','Omaha','NE','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (421,'Pendleton Park','PEN01','East End Park','Cincinnati','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (422,'Athletics Park; Twenty-Fifth and Jefferson Streets; Olympic Ball Ground','PHI01','Jefferson Street Grounds','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (423,'Centennial Grounds','PHI02','Centennial Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (424,NULL,'PHI03','Oakdale Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (425,NULL,'PHI04','Recreation Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (426,NULL,'PHI05','Keystone Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (427,'Philadelphia Baseball Grounds; National League Park','PHI06','Huntingdon Grounds I','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (428,'Brotherhood Park','PHI07','Forepaugh Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (429,'University of Penn. Athletic Field','PHI08','University of Pennsylvania Athletic Field','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (430,'Philadelphia Baseball Grounds; National League Park','PHI09','Baker Bowl','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (431,'Columbia Avenue Grounds','PHI10','Columbia Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (432,'Connie Mack Stadium','PHI11','Shibe Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (433,NULL,'PHI12','Veterans Stadium','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (434,NULL,'PHI13','Citizens Bank Park','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (435,'Philadelphia Baseball Grounds; National League Park','PHI14','Huntingdon Grounds II','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (436,'Bank One Ballpark','PHO01','Chase Field','Phoenix','AZ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (437,NULL,'PIT01','Union Park','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (438,NULL,'PIT02','Exposition Park I','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (439,NULL,'PIT03','Exposition Park II','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (440,'Union Park; 3A Park; the Coliseum','PIT04','Recreation Park','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (441,NULL,'PIT05','Exposition Park III','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (442,NULL,'PIT06','Forbes Field','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (443,NULL,'PIT07','Three Rivers Stadium','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (444,NULL,'PIT08','PNC Park','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (445,'Adelaide Park I','PRO01','Adelaide Avenue Grounds','Providence','RI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (446,'Messer Park; Messer Field','PRO02','Messer Street Grounds','Providence','RI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (447,'Fair Grounds Park','RCK01','Agricultural Society Fair Grounds','Rockford','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (448,NULL,'RIC01','Richmond Fair Grounds','Richmond','VA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (449,NULL,'RIC02','Allens Pasture','Richmond','VA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (450,NULL,'ROC01','Culver Field I','Rochester','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (451,NULL,'ROC02','Culver Field II','Rochester','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (452,NULL,'ROC03','Ontario Beach Grounds','Rochester','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (453,'St. George Grounds','SAI01','St. George Cricket Grounds','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (454,'San Diego Stadium; Jack Murphy Stadium; SDCCU Stadium','SAN01','Qualcomm Stadium','San Diego','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (455,NULL,'SAN02','Petco Park','San Diego','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (456,'Sick''s Seattle Stadium; Sicks'' Stadium','SEA01','Sick''s Stadium','Seattle','WA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (457,'King County Stadium','SEA02','Kingdome','Seattle','WA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (458,'Safeco Field','SEA03','T-Mobile Park','Seattle','WA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (459,NULL,'SFO01','Seals Stadium','San Francisco','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (460,'Bay View Stadium; 3Com Park; 3Com Park at Candlestick Point','SFO02','Candlestick Park','San Francisco','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (461,'Pacific Bell Park; SBC Park','SFO03','AT&T Park','San Francisco','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (462,'Hiram Bithorn Stadium','SJU01','Estadio Hiram Bithorn','San Juan',NULL,'PR');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (463,'Springfield Track','SPR01','Hampden Park Race Track','Springfield','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (464,'Red Stocking Base-Ball Park; Compton Avenue Park','STL01','Red Stocking Baseball Park','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (465,'Sportsman''s Park; Grand Avenue Park; Athletic Park','STL02','Grand Avenue Ball Grounds','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (466,'Grand Avenue Ball Grounds; Grand Avenue Park; Athletic Park','STL03','Sportsman''s Park I','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (467,'Union Base Ball Park; Lucas Park','STL04','Union Grounds','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (468,'New Sportsmans'' Park; League Park; Cardinal Field','STL05','Robison Field','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (469,NULL,'STL06','Sportsman''s Park II','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (470,'Busch Stadium I','STL07','Sportsman''s Park III','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (471,'Federal League Park','STL08','Handlan''s Park','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (472,'Busch Memorial Stadium','STL09','Busch Stadium II','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (473,NULL,'STL10','Busch Stadium III','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (474,'Florida Suncoast Dome; ThunderDome','STP01','Tropicana Field','St. Petersburg','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (475,'SCG','SYD01','Sydney Cricket Ground','Sydney','New South Wales','AU');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (476,'Newell Park','SYR01','Star Park I','Syracuse','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (477,NULL,'SYR02','Star Park II','Syracuse','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (478,NULL,'SYR03','Iron Pier','Syracuse','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (479,NULL,'THR01','Three Rivers Park','Three Rivers','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (480,NULL,'TOK01','Tokyo Dome','Tokyo','Tokyo','JP');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (481,NULL,'TOL01','League Park','Toledo','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (482,NULL,'TOL02','Tri-State Fair Grounds','Toledo','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (483,NULL,'TOL03','Speranza Park','Toledo','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (484,NULL,'TOL04','Armory Park','Toledo','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (485,'Canadian National Exhibition Stadium; CNE Stadium','TOR01','Exhibition Stadium','Toronto','ON','CA');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (486,'Ontario Stadium Project; SkyDome; Pan-Am Dome; Pan-Am Ceremonies Venue','TOR02','Rogers Centre','Toronto','ON','CA');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (487,'Vail''s Lot','TRO01','Haymakers'' Grounds','Troy','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (488,NULL,'TRO02','Putnam Grounds','Troy','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (489,'Rocky Point Amusement Park','WAR01','Rocky Point Park','Warwick','RI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (490,'Olympic Grounds; Olympic''s Grounds','WAS01','Olympic Grounds','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (491,NULL,'WAS02','National Grounds','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (492,'Capitol Park I','WAS03','Capitol Grounds','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (493,'Washington Athletic Park','WAS04','Athletic Park','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (494,'Capitol Park II','WAS05','Swampoodle Grounds','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (495,'American League Park II; National Park; Nationals'' Park','WAS06','Boundary Field','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (496,NULL,'WAS07','American League Park I','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (498,'National Park; American League Park','WAS09','Griffith Stadium','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (499,'Robert F. Kennedy Memorial Stadium; District of Columbia Stadium','WAS10','RFK Stadium','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (500,NULL,'WAS11','Nationals Park','Washington','DC','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (501,NULL,'WAT01','Troy Ball Club Grounds','Watervliet','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (502,'Waverly Park','WAV01','Waverly Fairgrounds','Waverly','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (503,'Monitor Park','WEE01','Monitor Grounds','Weehawken','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (504,NULL,'WHE01','Island Grounds','Wheeling','WV','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (505,NULL,'WIL01','Union Street Park','Wilmington','DE','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (506,'Memorial Field; Bowman Field; Historic Bowman Field; Muncy Bank Ballpark at Historic Bowman Field','WIL02','BB&T Ballpark at Bowman Field','Williamsport','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (507,'Weehawken Cricket Grounds','WNY01','West New York Field Club Grounds','West New York','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (508,'Worcester Driving Park','WOR01','Agricultural County Fair Grounds I','Worcester','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (509,'Worcester Driving Park','WOR02','Agricultural County Fair Grounds II','Worcester','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (510,NULL,'WOR03','Worcester Driving Park Grounds','Worcester','MA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (511,'Estadio Alfredo Harp Helú','MEX02','Alfredo Harp Helú Stadium','Mexico City','CDMX','MX');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (512,NULL,'DYE01','Field of Dreams','Dyersville','IA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (513,'Dunedin Stadium at Grant Field; Knology Park; Florida Auto Exchange Stadium','DUN01','TD Ballpark','Dunedin','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (514,'Pilot Field; Downtown Ballpark; North AmeriCare Park; Dunn Tire Park; Coca-Cola Field','BUF05','Sahlen Field','Buffalo','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (515,NULL,'ARL03','Globe Life Field','Arlington','TX','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (516,NULL,'SEO01','Gocheok Sky Dome','Seoul','Seoul','South Korea');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (517,NULL,'BIR01','Rickwood Field','Birmingham','AL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (518,'Fort Street Grounds; Fort Road Grounds','SPA01','West Seventh Street Park','St. Paul','MN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (519,'St. Mary''s Field','AKR01','League Park II','Akron','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (520,NULL,'ALG01','Fair Grounds','Algona','IA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (521,NULL,'ATC01','Bacharach Park','Atlantic City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (522,NULL,'ATC02','Inlet Park','Atlantic City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (523,NULL,'ATC03','Inlet Park II','Atlantic City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (524,'Spiller Park; Spiller Field','ATL04','Ponce De Leon Park','Atlanta','GA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (525,NULL,'BAL13','Bugle Field','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (526,NULL,'BAL14','Maryland Park','Baltimore','MD','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (527,'Sprague Field','BLO01','General Electric Field','Bloomfield','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (528,'New York Catholic Protectory','BNX01','Catholic Protectory Oval','Bronx','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (529,'Razzberry Park; 3rd and Erie','CAM01','3rd & Erie','Camden','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (530,NULL,'CHE01','Congoleum-Nairn Field','Chester','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (531,NULL,'CHE02','Felton Field','Chester','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (532,'Schorling''s Park I','CHI13','Auburn Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (533,NULL,'CHI14','Columbia Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (534,'Chase Park','CHI15','Gunther Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (535,NULL,'CHI16','Logan Square Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (536,NULL,'CHI17','Normal Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (537,'Osterman''s Red Sox park','CHI18','Red Sox Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (538,'37th and Butler St','CHI19','Union Park','Chicago','IL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (539,'Cleveland Hardware Field','CLE10','Hardware Field','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (540,'Luna Bowl','CLE12','Luna Park','Cleveland','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (541,'Hooper Field; Slavia Hooper Field','CLE11','Tate Field','Newburgh Heights','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (542,NULL,'COL05','Panhandle Park','Columbus','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (543,'West Side Park','DAY02','Westwood Field','Dayton','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (544,NULL,'DET06','Mack Park','Detroit','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (545,'Freeport Speedway; Freeport Municipal Stadium','FRE01','Municipal Stadium','Freeport','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (546,NULL,'FRL01','Pluto Park','French Lick','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (547,'Roesink Stadium','HAM01','Hamtramck Stadium','Hamtramck','MI','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (548,'City Island','HSB01','Island Park','Harrisburg','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (549,NULL,'HSB02','West End Grounds','Harrisburg','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (550,'East Ohio Street Grounds; League Park','IND08','Northwestern Park','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (551,'Owen J. Bush Stadium; Bush Stadium; Victory Field I','IND09','Perry Stadium','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (552,'Washington Baseball Park; Washington Baseball Grounds; West Washington Street Park','IND10','Washington Park II','Indianapolis','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (553,'J. P. Small Memorial Stadium; Barrs Field; Myrtle Avenue Ball Park; Red Cap Stadium','JAX01','Durkee Field','Jacksonville','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (554,'Skeeters Park','JER03','West Side Park','Jersey City','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (555,NULL,'KAN07','Association Park II','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (556,NULL,'KAN08','Riverside Park','Kansas City','KS','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (557,NULL,'KAN09','Shelley Park','Kansas City','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (558,'Colonels Field','LOU05','Parkway Field','Louisville','KY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (559,'Crump''s Park','LRO01','Crump Park','Little Rock','AR','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (560,'State Hospital Field','MDN01','State Hospital Grounds','Middletown','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (561,NULL,'MEA01','Athletic Park','Meadville','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (562,'Martin Stadium; Martin Park','MEM01','Lewis Park','Memphis','TN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (563,'Elm Wood Park; Red Elm Park','MEM02','Russwood Park','Memphis','TN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (564,NULL,'MNR01','Casino Park','Monroe','LA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (565,NULL,'MTG01','College Hill Park','Montgomery','AL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (566,'Heinemann Park','NOL01','Pelican Stadium','New Orleans','LA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (567,'Sulphur Spring Park; Athletic Park','NSH01','Sulphur Dell','Nashville','TN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (568,'Tom Wilson Park','NSH02','Wilson Park','Nashville','TN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (569,'Ruppert Stadium; Davids'' stadium','NWK02','Davids Stadium','Newark','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (570,'Ollemar Field','NWK03','Ollemar Stadium','Irvington','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (571,NULL,'NYC22','Brighton Oval','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (572,NULL,'NYC23','Dexter Park','Queens','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (573,NULL,'NYC24','Dyckman Oval','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (574,NULL,'NYC25','Lenox Oval','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (575,NULL,'NYC26','Meyerrose Park','Queens','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (576,NULL,'NYC27','New York Oval','Bronx','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (577,NULL,'NYC28','Olympic Field','New York','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (578,NULL,'NYC29','Saratoga Park','Brooklyn','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (579,'Saratoga Park','OKC01','Colcord Park','Oklahoma City','OK','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (580,NULL,'PAT01','Hinchliffe Stadium','Paterson','NJ','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (581,'P.R.R. YMCA Athletic Field; PRR-YMCA Field; Penmar Park; Parkside Athletic Field; 44th and Parkside ballpark','PHI15','44th & Parkside','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (582,NULL,'PHI16','Passon Field','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (583,'Bala Cynwyd Park; Pencoyd Park','PHI17','Pencoyd Field','Philadelphia','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (584,'Central Amusement Park','PIT09','Central Park','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (585,NULL,'PIT10','Greenlee Field','Pittsburgh','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (586,'Silver Stadium','ROC04','Red Wing Stadium','Rochester','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (587,'Van Slyck Island','SCH01','Island Park','Schenectady','NY','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (588,NULL,'SPA02','Downtown Park','St. Paul','MN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (589,NULL,'STL11','Brock''s Park','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (590,'Christian Brothers College High School; CBC High School','STL12','Christian Brothers College Diamond','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (591,'Metropolitan Park','STL13','Giants Park II','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (592,'Kuebler''s Park; Giants Park I','STL14','Kuebler Park','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (593,'South End Park; National Nite Baseball Park','STL15','South End Grounds','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (594,NULL,'STL16','Stars Park','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (595,'Tigers'' Field; Tigers Field','STL17','Tiger Field','St. Louis','MO','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (596,NULL,'TOL05','Swayne Field','Toledo','OH','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (597,NULL,'WBS01','Sprudel Park','West Baden Springs','IN','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (598,NULL,'WIL03','Harlan Field','Wilmington','DE','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (599,NULL,'YEA01','Hilldale Park','Yeadon','PA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (600,NULL,'SAC01','Sutter Health Field','West Sacramento','CA','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (601,'Legends Field','TAM02','George M. Steinbrenner Field','Tampa','FL','US');
INSERT INTO Parks(ID,parkalias,parkkey,parkname,city,state,country) VALUES (602,'Bristol International Raceway; Bristol International Speedway','BST01','Bristol Motor Speedway','Bristol','TN','US');
