INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('AB','Algona Brownies','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('AB2','Indianapolis ABCs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ABC','Indianapolis ABCs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('AC1','All Cubans','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('AC2','All Cubans','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ACG','Akron Grays / Cleveland Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ALT','Altoona Mountain City','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ANA','Los Angeles Angels of Anaheim','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ARI','Arizona Diamondbacks','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ATH','Philadelphia Athletics','N','PNA');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ATL','Atlanta Braves','Y','BNA');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BAL','Baltimore Orioles','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BBB','Birmingham Black Barons','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BBS','Baltimore Black Sox','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BCA','Atlanta Black Crackers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BEG','Baltimore Elite Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BFB','Buffalo Bisons','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BFL','Buffalo Bisons','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BG1','Atlantic City Bacharach Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BG2','Atlantic City Bacharach Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BLC','Baltimore Canaries','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BLO','Baltimore Orioles','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BLT','Baltimore Terrapins','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BLU','Baltimore Monumentals','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BNA','Boston Red Stockings','NA','ATL');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BOS','Boston Red Sox','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BR2','Brooklyn Royal Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BRA','Brooklyn Atlantics','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BRD','Boston Reds','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BRG','Brooklyn Gladiators','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BRS','Boston Reds','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BTT','Brooklyn Tip-Tops','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BUF','Buffalo Bisons','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('BWW','Brooklyn Ward''s Wonders','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CAG','Chicago American Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CBB','Columbus Blue Birds','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CBE','Cleveland Buckeyes','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CBG','Cuban Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CBK','Columbus Buckeyes','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CBL','Cleveland Blues','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CBN','Cleveland Browns','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CCG','Chicago Columbia Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CEL','Cleveland Elites','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CEN','Philadelphia Centennials','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CFC','Cleveland Forest Citys','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CHC','Chicago Cubs','Y','CNA');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CHH','Chicago Whales','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CHP','Chicago Pirates','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CHT','Cleveland Hornets','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CHW','Chicago White Sox','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CIN','Cincinnati Reds','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CIU','Chicago Unions','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CKK','Cincinnati Kelly''s Killers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CL2','Cleveland Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CLE','Cleveland Indians','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CLI','Cleveland Infants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CLS','Columbus Solons','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CLV','Cleveland Spiders','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CNA','Chicago White Stockings','NA','CHC');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CNR','Cincinnati Reds','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('COB','Columbus Buckeyes','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('COG','Chicago Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('COL','Colorado Rockies','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('COR','Cincinnati Outlaw Reds','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('COT','Columbus Turf Club','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CPI','Chicago/Pittsburgh (Union League)','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CRS','Cleveland Red Sox','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CSE','Cuban Stars East','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CSW','Cuban Stars West','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CT','Cincinnati Tigers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CTG','Cleveland Tigers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CTS','Cleveland Tate Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CUP','Pollock''s Cuban Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('CXG','Cuban X Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('DET','Detroit Tigers','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('DS','Detroit Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('DTN','Detroit Wolverines','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('DTS','Detroit Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('DW','Detroit Wolves','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('DYM','Dayton Marcos','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ECK','Brooklyn Eckfords','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('FLA','Florida Marlins','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('FLP','French Lick Plutos','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('GOR','New York Gorhams','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('HAR','Hartford Dark Blues','N','HNA');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('HBG','Harrisburg Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('HG','Homestead Grays','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('HIL','Hilldale Club','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('HNA','Hartford Dark Blues','NA','HAR');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('HOU','Houston Astros','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('IA','Indianapolis Athletics','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('IBL','Indianapolis Blues','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('IC','Cincinnati-Indianapolis Clowns','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('IHO','Indianapolis Hoosiers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('IND','Indianapolis Hoosiers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('JRC','Jacksonville Red Caps','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCC','Kansas City Cowboys','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCG','Kansas City Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCM','Kansas City Monarchs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCN','Kansas City Cowboys','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCP','Kansas City Packers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCR','Kansas City Royals','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KCU','Kansas City Cowboys','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KEK','Fort Wayne Kekiongas','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('KRG','Kansas City Royal Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('LAD','Los Angeles Dodgers','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('LEL','Chicago Leland Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('LGR','Louisville Grays','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('LOU','Louisville Colonels','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('LRG','Little Rock Grays','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('LVB','Louisville Black Caps','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MAN','Middletown Mansfields','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MAR','Baltimore Marylands','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MB','Milwaukee Bears','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MGS','Montgomery Grey Sox','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MIL','Milwaukee Brewers','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MIN','Minnesota Twins','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MLA','Milwaukee Brewers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MLG','Milwaukee Grays','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MLU','Milwaukee Brewers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MOH','Schenectady Mohawk Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MRM','Monroe Monarchs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('MRS','Memphis Red Sox','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NAT','Washington Nationals','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NBY','New York Black Yankees','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ND','Newark Dodgers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NE','Newark Eagles','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NEW','Newark Pepper','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NHV','New Haven Elm Citys','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NLG','New York Lincoln Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NLS','New York Lincoln Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NNA','New York Mutuals','NA','NYU');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NS','Newark Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NWB','Newark Browns','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NYC','New York Cubans','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NYI','New York Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NYM','New York Mets','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NYP','New York Metropolitans','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NYU','New York Mutuals','N','NNA');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('NYY','New York Yankees','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('OAK','Oakland Athletics','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('OKM','Oklahoma Monarchs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('OLY','Washington Olympics','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PBB','Pittsburgh Burghers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PBG','Philadelphia Bacharach Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PBK','Pittsburgh Keystones','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PBS','Pittsburgh Rebels','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PC','Pittsburgh Crawfords','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PG','Philadelphia Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PHA','Philadelphia Athletics','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PHI','Philadelphia Phillies','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PHK','Philadelphia Keystones','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PHQ','Philadelphia Athletics','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PIT','Pittsburgh Pirates','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PNA','Philadelphia Athletics','NA','ATH');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PRO','Providence Grays','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PS','Philadelphia Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PTG','Philadelphia Tigers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('PWS','Philadelphia White Stockings','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('QG','Philadelphia Quaker Giants','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('RES','Elizabeth Resolutes','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('RIC','Richmond Virginians','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ROC','Rochester Broncos','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('ROK','Rockford Forest Citys','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SBS','St. Louis Brown Stockings','N','SNA');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SC1','Stars of Cuba','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SDP','San Diego Padres','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SEA','Seattle Mariners','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SEN','Washington Black Senators','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SFG','San Francisco Giants','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SL2','St. Louis Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SLI','St. Louis Terriers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SLM','St. Louis Maroons','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SLR','St. Louis Red Stockings','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SLS','St. Louis Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SNA','St. Louis Brown Stockings','NA','SBS');
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SNH','St. Louis-New Orleans Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SPG','St. Paul Gophers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('STL','St. Louis Cardinals','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('STP','St. Paul Apostles','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SYR','Syracuse Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('SYS','Syracuse Stars','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TBD','Tampa Bay Rays','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TEX','Texas Rangers','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TLM','Toledo Maumees','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TOL','Toledo Blue Stockings','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TOR','Toronto Blue Jays','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TRO','Troy Haymakers','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TRT','Troy Trojans','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('TT','Toledo Tigers','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WAP','Washington Pilots','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WAS','Washington Senators','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WBL','Washington Blue Legs','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WBS','West Baden Sprudels','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WES','Keokuk Westerns','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WIL','Wilmington Quicksteps','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WNA','Washington Nationals','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WNL','Washington Nationals','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WNT','Washington Nationals','NA',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WOR','Worcester Ruby Legs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WP','Washington Potomacs','N',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WSN','Washington Nationals','Y',NULL);
INSERT INTO TeamsFranchises(franchID,franchName,active,NAassoc) VALUES ('WST','Washington Statesmen','N',NULL);